export const quizResultSummaryStyles = {
  root: "space-y-6",
  heroCard:
    "rounded-[2rem] border border-white/70 bg-white/80 p-6 shadow-[0_30px_90px_rgba(15,23,42,0.08)] md:p-8",
  heroLayout: "flex flex-col gap-6 lg:flex-row lg:items-center lg:justify-between",
  eyebrow: "text-sm font-semibold uppercase tracking-[0.24em] text-cyan-700",
  title: "mt-3 text-3xl font-semibold tracking-tight text-slate-900",
  description: "mt-3 max-w-2xl text-sm leading-6 text-slate-500",
  scoreBadge:
    "flex h-40 w-40 items-center justify-center rounded-full bg-[radial-gradient(circle_at_top,#67e8f9,transparent_55%),linear-gradient(135deg,#0f172a,#155e75)] text-white shadow-[0_20px_60px_rgba(8,145,178,0.35)]",
  scoreContent: "text-center",
  scoreLabel: "text-xs uppercase tracking-[0.24em] text-cyan-100",
  scoreValue: "mt-2 text-5xl font-semibold",
  generationNote: "rounded-[1.75rem] border border-amber-200 bg-amber-50 px-5 py-4 text-sm leading-6 text-amber-800",
  statsGrid: "grid gap-4 md:grid-cols-3",
  correctStat: "rounded-[1.75rem] bg-slate-900 p-5 text-white shadow-lg shadow-slate-900/15",
  statIcon: "h-5 w-5 text-cyan-300",
  darkStatLabel: "mt-4 text-sm text-slate-300",
  darkStatValue: "mt-2 text-3xl font-semibold",
  statCard: "rounded-[1.75rem] bg-white/80 p-5 shadow-[0_20px_60px_rgba(15,23,42,0.08)]",
  statLabel: "text-sm text-slate-500",
  statValue: "mt-2 text-3xl font-semibold text-slate-900",
  detailGrid: "grid gap-4 lg:grid-cols-[0.95fr_1.05fr]",
  detailCard: "rounded-[1.75rem] bg-white/80 p-6 shadow-[0_20px_60px_rgba(15,23,42,0.08)]",
  sectionTitle: "text-sm font-semibold uppercase tracking-[0.2em] text-slate-400",
  topics: "mt-4 flex flex-wrap gap-2",
  weakTopic: "rounded-full bg-amber-50 px-3 py-1.5 text-sm font-medium text-amber-700",
  clearTopic: "rounded-full bg-emerald-50 px-3 py-1.5 text-sm font-medium text-emerald-700",
  recommendationHeader: "flex items-center gap-3",
  recommendationIcon: "h-5 w-5 text-cyan-600",
  recommendations: "mt-4 space-y-3",
  recommendationItem: "flex items-start gap-3 rounded-2xl bg-slate-50 px-4 py-3 text-sm leading-6 text-slate-600",
  recommendationArrow: "mt-1 h-4 w-4 flex-none text-cyan-600",
  actions: "flex flex-col gap-3 sm:flex-row sm:flex-wrap",
  primaryButton:
    "inline-flex items-center gap-2 rounded-full bg-slate-900 px-6 py-3 text-sm font-semibold text-white shadow-lg shadow-slate-900/20 transition hover:bg-slate-800",
  secondaryButton:
    "inline-flex items-center gap-2 rounded-full border border-slate-200 bg-white px-6 py-3 text-sm font-semibold text-slate-700 transition hover:border-slate-300 hover:text-slate-900",
  actionIcon: "h-4 w-4",
};
